### ISSUE TITLE
Add Shinken to Offrelibre program

### ISSUE THREAD

**Issue by titilambert** [naparuba/shinken#1436]
I think, it could be really cool to get it for Shinken : http://offrelibre.com/
What to you think ?

**Comment by naparuba** [comment]
As the shinken editor (shinken solution) is also writing proprietary
programs, seems a very strange idea, and I don't see any real community
advantage for this, it's only business linked about professionnal offers.

For a side note, I think users don't need a label for open source programs
in France (the label is only limited to france and it's another reason to
avoid it as you will have problem with a double communication channel)
because company don't really care about "open source" (as in "code is
open").

I think such label can have a far more powerful impact in the US from a big
company like RedHat.

But it's off topic and if you want we can continue in irc intead :)


Jean
