### ISSUE TITLE
Receiver error in external command processing

### ISSUE THREAD

**Issue by andyxning** [naparuba/shinken#1491]
Receiver can receive and resolve_command external commands, however, in processing external commands, besides external commands with __host__ and __service__ in the __args__ in External Commands, resolve_command method will not put these external commands to the global, i.e. all schedulers. because if the __mode__ of externalcommandmanager is 'receiver', it will return with the python code like below:
```
# If we are a receiver, bail out here
if self.mode == 'receiver':
   return
```
So, i think this will lose some external commands.

**Comment by Seb-Solon** [comment]
Actually, it's more complicated. there are some other if like that in external command. Receiver send the command to scheduler. The code after the return is for scheduler basically. The receiver will send command with post query etc, it cannot execute the command because it does not have data. 

This is more or less the same behavior when the arbiter is receiving external command. All command are finally sent to the scheduler that run them.
