### ISSUE TITLE
Retention for global enable_notifications is not working as expected

### ISSUE THREAD

**Issue by exi2163** [naparuba/shinken#1529]
Hi,

i am running shinken 2.2 installed from pip and i've got a problem with retention of enable_notifications.

I use Thruk on livestatus to disable global notifications. The external command is working and gets executed, the state is switched to notifications_enabled=0 and no notifications are sent.

If i restart the arbiter it will send the scheduler a new config with notifications_enabled=1. 
If i restart the scheduler it will first load the retention data with notifications_enabled=0 and then gets a config from arbiter with notifications_enabled=1.

I've also tested the notification state for host and service which are working fine.

A reverse test shows the same behaviour:
Setting enable_notifications=0 in the main conf results in notifications_enabled=0 beeing pushed to the scheduler.
Switching notifications_enabled to 1 via ext cmd and then restarting scheduler or arbiter will reset notifications_enabled to 0.

Summary:
The config value of enable_notifications overwrites the current state on config dispatch.

**Comment by gst** [comment]
Hi,

effectively this **looks like** rather a buggy behavior.

**Because** : you could think of the (re)start of the arbiter as if you had done/executed plenty of external commands (with each such parameter/value (re)set to its configured(or default) value) for every host/service/contact actually defined.. and then it's not anymore a bug but **the correct behavior** !!!

Now, I agree that if the scheduler stores the different hosts/services/contacts states with/for retention then in this case it should also be able to (more) correctly handle this situation.

So this should be corrected/managed at the scheduler level I think : if it receives a new config from the arbiter then it should probably "merge" it with whatever current config it has (when it has already one so), handling correctly such different values for the same parameter on the old and new config.

Now the harder thing is : how to do that ! :p

**Comment by Seb-Solon** [comment]
Actually it should be already done. The point is the priority of the conf from the arbiter vs retention.

**Comment by gst** [comment]
> Actually it should be already done.

you mean the "merge" of an old and new config at the scheduler level :-?

**Comment by Seb-Solon** [comment]
as far as i remember  the conf is loaded and then retention is loaded an override object. For the reload I should have a look.

**Comment by Seb-Solon** [comment]
Mhh actually. The process is the same AFAIK for reoad. 
* Sched get the new conf from arb
* Sched load conf (objects)
* Sched load module (retention module included)
* Sched load retention and onverride parameters in objects at least.  I should check for global like this one

**Comment by Seb-Solon** [comment]
I've just read the code and as far as I can see, there is only service and host saved in retention not global values. So no retention in invovled. 

In my opinion this is a normal behavior, global paramter are reset after restart, the config file are made to specify this kind of switch.
