### ISSUE TITLE
Exposing all shinken monitoring managment features through django rest framework

### ISSUE THREAD

**Issue by auvipy** [naparuba/shinken#1736]
is it possible to expose shinken features through rest api? so that can be used from android/django backends?

**Comment by naparuba** [comment]
Do you have any example of such features you want to be exposed? All
daemons are already exchanging with http, but mainly for internal calls.

So what do you want as API, which features exactly?

**Comment by auvipy** [comment]
I want to expose them publicly :)

**Comment by auvipy** [comment]
so that I can manipulate them from mobile apps/web apps

**Comment by naparuba** [comment]
ok but please let me know which feature you want to be exposed in shinken
framework, because aside daemon state and stats, there is nothing to be
used by the external worlds (all are inner calls like push conf or such
things).

So what do you want as API calls exaclty?

thanks :)

**Comment by auvipy** [comment]
well the idea is that I want to control daemons from web console/mobile app. like checking process/stop/restart/add daemon[if possible]

**Comment by auvipy** [comment]
i found bottle+bottleUI looking at the core. but django is the most widely used framework so my intension is using shinken core modules for monitoring but controling/extending them by using django framework/rest/angularvuejs etc.

**Comment by naparuba** [comment]
bottle is enough for building a REST in the framework, you can use what you
want for your other tools if you prefer django :)


currently there is nothing for controling the daemosn (stop/start) because
all is managd externaly (init.d or systemd script), and I think that it
should not to the framework to manage this directly (or we will need a top
level daemon that will start/stop/manage others, so in the end we will code
something like a sub-systemd, and so won't be so useful).

You should look for other tools that are done to manage/extend clsuters,
like docker and/or kubertenes. They are done for such things, and with them
you will be able to add/manage/delete/extend new daemons. I'm sure they
have all the REST API you will need to build your cluster management system.

Because after all it's what they are done for ^^

**Comment by auvipy** [comment]
well i need to expose the stats/monitoring features to be exposed through REST, that sgould be possible?

**Comment by naparuba** [comment]
stats yes, but monitoring no because the framework do not export them (it's
a module role, not to the famework).

you should look at livestatus (with a wrapper) or webui2/mod-rest if you
need monitoring data in REST mode.

**Comment by mohierf** [comment]
@naparuba : which webui2/mod-rest module? It does not exist and Webui2 is not related to this module (that is an empty repo ...) ...

@auvipy: unfortunately, Shinken does not expose any REST API that complies to your requirements ...

**Comment by auvipy** [comment]
im experimenting my solutions/POC

**Comment by naparuba** [comment]
I you want something special tht can be use y everyone, please propose a pull request :)
