### ISSUE TITLE
command in notification does not receive NAGIOS_ environment variables

### ISSUE THREAD

**Issue by amarao** [naparuba/shinken#1780]
Documentation in http://shinken.readthedocs.org/en/latest/05_thebasics/macros.html#macros-as-environment-variables states that all commands runs with environments variables  NAGIOS_* assigned to corresponding macros values (citation from documentation: $HOSTNAME$ macro would be available as an environment variable named “NAGIOS_HOSTNAME”).

In contrast, current version of shinken does not set a single environment variable with NAGIOS_ prefix while calling a command for notifications.

(I peeked a little inside code and I think that env=... named argument is not set during Notification class initialisation in shinken/objects/schedulingitem.py, but I'm not sure);

**Comment by geektophe** [comment]
This feature has to be manually enabled by setting `enable_environment_macros` to `1`. It may be done globally by setting it in the main configuration file, or it may be set for a specific command by setting it in the command object definition.

In `shinken.cfg`

    enable_environment_macros = 1

In command object

    define command {
        command_name ...
        command_line ...
        enable_environment_macros 1
    }

It is disabled by default, and it is highly recommended to only enable it where it's needed, because it involves higher CPU usage on scheduler side.

**Comment by amarao** [comment]
Thanks!

Yes, it works. Perhaps, it should be noted in the http://shinken.readthedocs.org/en/latest/05_thebasics/macros.html#macros-as-environment-variables (and notice about performance too).

**Comment by geektophe** [comment]
I'll do so.
