### ISSUE TITLE
Tell about the sqlite alternative in the webui documentation

### ISSUE THREAD

**Issue by JulienPalard** [naparuba/shinken#1862]
Here http://shinken.readthedocs.io/en/latest/11_integration/webui.html, only mongodb is proposed, I really think sqlite should be documented here, even proposed by default.

**Comment by mohierf** [comment]
The most recent versions of the Web UI are not tested nor maintained with the sqlite ... sorry for this but we choose to use MongoDB as a centrak repository for the WebUI.

**Comment by JulienPalard** [comment]
Is this decision documented somewhere? I mean the pros/cons of using mongodb for this? It look like a really bad choice from my personal point of view, so I'm interested in backlogging the debate on the subject, possibly to change my mind (always keep an open mind ^^).

**Comment by ddurieux** [comment]
If we modify, it mean recode a big part.

So why it's a bad choice for you? you don't give really explanations :p

**Comment by JulienPalard** [comment]
No, I though it was more productive to read your internal debate (if it happened) that starting another one. But from my _very personal_ point of view* the only usefull usage of MongoDB is when you can't store your data on say 10 or 100 servers. To store less than that, using MongoDB is just playing with its drawbacks (legitimates ones, by design). So to keep just a bunch of data on a single server, even probably a single process, I think SQLite (among others) is more appropriated.

I may have missed something, like the usecase when you actually have to store a few petabytes of logs and map-reduce them in a cron overnight, in which case it's perfectly legitimate to use MongoDB and using SQLite is just impossible: I'm new to Skinken.

Note that I'm not here to start a furious troll/debate, neither to help rewriting all your code to switch to sqlite: "if it works, don't fix it"? I just though (by reading the doc / conf file) that both alternatives was actually implemented and both worked already, so I inferred you're only storing a bunch of values in it, then I though presenting sqlite instead of mongodb as a default would be more appropriated (and simplier to install, manage, faster (no TCP connexion, we're speaking of only a bunch of values), lighter, just specialized for the job...).

*: I used both, MongoDB in production, SQLite only personally, but still it's probably a personal taste

**Comment by ddurieux** [comment]
For store many key=>values  mongo is ok, and it's scalable (you can't with sqlite)

**Comment by mohierf** [comment]
@JulienPalard 

The internal debate occured by phone ... and the main reasons to choose MongoDB where that MongoDB is the only DB that has Shinken modules for storing logs and retention data, and we wanted the Web UI to have such features ...

 Furthermore, the SQLite module is no more mainteained and we did not want to maintain several DB for Web UI parameters.

 I agree with your arguments ... it should be interesting to have a lighter DB configuration to store only some few parameters for the Web UI. If you have the need and a few time to develop the SQLite part of this feature I can help and give you some hints to dive into the source code for this ... it will not be very difficult because we implemented a kind of plugin for such features ... ?

**Comment by naparuba** [comment]
for webui / webui2 doc part.
