### ISSUE TITLE
notifications_enabled seems not to work when nesting hostgroups

### ISSUE THREAD

**Issue by nmaupu** [naparuba/shinken#633]
the directive notifications_enabled does not work when applied to hostgroup of hostgroups.

example :
define hostgroup {
  hostgroup_name        test_hg
  alias                 test_hg
  members               machine1, machine2
}

define hostgroup {
  hostgroup_name        test_hghg
  alias                 test_hghg
  members               test_hg
}

-> This disable notifications as expected
define service {
  use                           generic-service, no-importance
  hostgroup_name                test_hg
  service_description           Load
  check_command                check_snmp_load!5.0,4.0,3.0!10.0,6.0,4.0
}

-> This DOES NOT disable notifications
define service {
  use                           generic-service, no-importance
  hostgroup_name                test_hghg
  service_description           Load
  check_command                check_snmp_load!5.0,4.0,3.0!10.0,6.0,4.0
}

Do you guys have the same problem ?

**Comment by Alex85651** [comment]
Hi, sorry for answering to this old post but it seems like I have a similar problem with the notifications.
I use retention-mongodb with Shinken and when I try to change the value of notifications_enabled, it does not change in Shinken. It keeps the first value I gave him.
Do you know if there has been changes since this issue has been opened or is the problem still there ?

**Comment by Alex85651** [comment]
I found the solution!
I just removed the attribute retention from the definition of the property notification_enabled in objects/host.py
`'notifications_enabled':
            BoolProp(default=True, fill_brok=['full_status']),`
